### PR TITLE
Fix hypertable down-migration

### LINKED ISSUE #133: Hypertables cannot be downgraded
Currently, attempting to migrate down from step 18 (on `v5`) fails when attempting to drop `eth.header_cids` due to the dependency of stored functions on that table. This step attempts to migrate the data back to regular tables and then swap out the names, but Postgres does not provide a way to do this atomically and preserve the table's dependencies.

Proposed fix is to create an identical, but independent composite type used in the interface of the functions.

Note: CI tests needed to catch this https://github.com/cerc-io/ipld-eth-db/issues/121

### PR DESCRIPTION
**Pull request by roysc**
Fixes https://github.com/cerc-io/ipld-eth-db/issues/133 by renaming the indexes back to their original names after migrating out of the hypertables, so that stepping down at `12` will work.
Side note, the `storage_leaf_key_index` was being dropped but never existed.

Note, this will slightly clobber https://github.com/cerc-io/ipld-eth-db/pull/137. I can rebase on that if we want to merge it first.

### CODE REVIEW

File: db/migrations/00012_create_cid_indexes.sql [hunk 1]
```diff
@@ -64,7 +64,6 @@ DROP INDEX eth.log_block_number_index;
 DROP INDEX eth.storage_removed_index;
 DROP INDEX eth.storage_header_id_index;
 DROP INDEX eth.storage_cid_block_number_index;
-DROP INDEX eth.storage_leaf_key_index;
```
Comment (i-norden) [inline db/migrations/00012_create_cid_indexes.sql:67]: Ahh yeah in v4 when the PK was around paths not leaf_keys we had this index declared, but now the PK handles indexing on the `storage_leaf_key` field.

**Review by i-norden — APPROVED** [review]
LGTM, thanks! Will leave merge order between this and #137 up to you and Thomas.

**Comment by roysc** [comment]
Rebased on @telackey's PR and patched. For some reason I lost write access to this repo, so I can't merge.
